version: '3.3'
services: 
    build-demo:
        build: ./flask_calculator/
        volumes: 
            - ./flask_calculator/:/usr/src/app/
        ports: 
            - 5000:5000
        environment: 
            PORT: 5000
            FLASK_DEBUG: 1
